services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: encino_orm_test
    ports: ["3306:3306"]

  mariadb:
    image: mariadb:11
    environment:
      MARIADB_ROOT_PASSWORD: admin
      MARIADB_DATABASE: encino_orm_test
    ports: ["3307:3306"]

  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: encino_orm_test
    ports: ["5432:5432"]

  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Admin_123"
    ports: ["1433:1433"]

  oracle:
    image: gvenzl/oracle-xe:21-slim
    environment:
      ORACLE_PASSWORD: admin
    ports: ["1521:1521"]

  redis:
    image: redis:latest
    ports: ["6379:6379"]