import os
from typing import ClassVar

import pytest

from encino_orm import OracleDb, Query
from encino_orm.introspection.types import _normalize
from encino_orm.model import Filter, Model
from encino_orm.model.types import ddl_type
from encino_orm.oracle import _to_oracle
from tests.conftest import engine_unavailable

ORACLE_CONFIG = {
    "host": os.getenv("ENCINO_ORM_ORACLE_HOST", "127.0.0.1"),
    "port": int(os.getenv("ENCINO_ORM_ORACLE_PORT", "1521")),
    "service_name": os.getenv("ENCINO_ORM_ORACLE_SERVICE", "XEPDB1"),
    "user": os.getenv("ENCINO_ORM_ORACLE_USER", "system"),
    "password": os.getenv("ENCINO_ORM_ORACLE_PASSWORD", "admin"),
}


class _FakeError:
    def __init__(self, code):
        self.code = code


class _FakeExc(Exception):
    def __init__(self, code):
        self.args = (_FakeError(code),)


class TestOracleInternal:
    def test_to_oracle_named_binds(self):
        q = Query("SELECT * FROM t WHERE a = {0} AND b = {1}", [1, "x"])
        sql, values = _to_oracle(q.query[0], q.query[1])
        assert sql == "SELECT * FROM t WHERE a = :parameter_0000 AND b = :parameter_0001"
        assert values == {"parameter_0000": 1, "parameter_0001": "x"}

    def test_insert_builder_with_returning(self):
        db = OracleDb()
        sql, values = db._prepare(db.insert("t", {"a": 1, "b": "x"}))
        assert sql == (
            "INSERT INTO t (a,b) VALUES (:parameter_0000,:parameter_0001) RETURNING id INTO :ret_id"
        )
        assert values == {"parameter_0000": 1, "parameter_0001": "x"}

    def test_insert_builder_ignore_duplicated_flag(self):
        db = OracleDb()
        q = db.insert("t", {"a": 1}, ignore_duplicated=True)
        assert q.ignore_duplicated is True
        sql, _ = db._prepare(q)
        assert sql == "INSERT INTO t (a) VALUES (:parameter_0000) RETURNING id INTO :ret_id"

    def test_insert_builder_replace_merge_no_as(self):
        db = OracleDb()
        q = db.insert("t", {"a": 1, "b": "x"}, replace=True)
        sql, values = db._prepare(q)
        assert sql == (
            "MERGE INTO t dst USING (SELECT :parameter_0000 AS a, :parameter_0001 AS b) src "
            "ON (dst.a = src.a) "
            "WHEN MATCHED THEN UPDATE SET dst.a = src.a, dst.b = src.b "
            "WHEN NOT MATCHED THEN INSERT (a,b) VALUES (src.a,src.b)"
        )
        assert values == {"parameter_0000": 1, "parameter_0001": "x"}

    def test_update_builder(self):
        db = OracleDb()
        sql, values = db._prepare(db.update("t", {"id": 1}, {"nombre": "mod"}))
        assert sql == "UPDATE t SET nombre = :parameter_0000 WHERE id = :parameter_0001"
        assert values == {"parameter_0000": "mod", "parameter_0001": 1}

    def test_is_unique_violation(self):
        db = OracleDb()
        assert db.is_unique_violation(_FakeExc(1)) is True  # ORA-00001
        assert db.is_unique_violation(_FakeExc(2291)) is False  # ORA-02291 FK

    def test_is_lock_error(self):
        db = OracleDb()
        assert db.is_lock_error(_FakeExc(60)) is True  # ORA-00060 deadlock
        assert db.is_lock_error(_FakeExc(54)) is True  # ORA-00054 lock timeout
        assert db.is_lock_error(_FakeExc(8177)) is True  # ORA-08177 serialization
        assert db.is_lock_error(_FakeExc(1)) is False

    def test_normalize_new_types(self):
        assert _normalize("varchar2(255)") == ("str", 255, False)
        assert _normalize("nvarchar2(100)") == ("str", 100, False)
        assert _normalize("clob")[0] == "str"
        assert _normalize("blob")[0] == "blob"
        assert _normalize("raw(16)")[0] == "blob"
        assert _normalize("binary_double")[0] == "float"

    def test_ddl_map(self):
        assert (
            ddl_type("pk", "oracle")
            == "NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY"
        )
        assert ddl_type("str", "oracle") == "VARCHAR2(255)"
        assert ddl_type("bool", "oracle") == "NUMBER(1)"
        assert ddl_type("json", "oracle") == "CLOB"


@pytest.fixture
async def oracle_connected_db():
    db = OracleDb()
    try:
        await db.connect(**ORACLE_CONFIG)
    except Exception as e:
        engine_unavailable("oracle", e)
    yield db
    await db.close()


class _ParityModel(Model):
    """Modelo de paridad DIAL-03/DIAL-09 contra el motor real."""

    _table = "test_parity"
    nombre: str | None = None
    monto: float | None = None


class _MergeModel(Model):
    """Modelo para la regresión del MERGE: sin campos `datetime`.

    `Model._serialize` convierte `datetime`->`str` y Oracle no puede ligar ese
    string a una columna `TIMESTAMP` (ORA-01843) — limitación preexistente del
    camino de modelo, ajena a este plan. Se excluyen `created_at`/`updated_at`
    para que la sentencia MERGE sea realmente ejecutable.
    """

    _table = "test_parity"
    _fields_disabled: ClassVar[list] = ["created_at", "updated_at"]
    nombre: str | None = None
    monto: float | None = None


_PARITY_DDL = (
    "CREATE TABLE test_parity ("
    "id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY, "
    "nombre VARCHAR2(50), monto NUMBER, enabled NUMBER(1) DEFAULT 1, "
    "created_at TIMESTAMP, updated_at TIMESTAMP)"
)
_PARITY_DDL_SIN_MONTO = (
    "CREATE TABLE test_parity ("
    "id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY, "
    "nombre VARCHAR2(50), enabled NUMBER(1) DEFAULT 1, "
    "created_at TIMESTAMP, updated_at TIMESTAMP)"
)
_DROP_PARITY = (
    "BEGIN EXECUTE IMMEDIATE 'DROP TABLE test_parity'; "
    "EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;"
)


async def _reset_parity(db, ddl):
    await db._execute_raw(_DROP_PARITY)
    await db._execute_raw(ddl)


async def _seed_parity(db):
    for nombre, monto in [("Ana", 10.0), ("Luis", 20.0), ("Eva", 30.0)]:
        await db.execute(db.insert("test_parity", {"nombre": nombre, "monto": monto}))


@pytest.mark.integration
@pytest.mark.optional_engine
class TestOracleLifecycle:
    @pytest.mark.asyncio
    async def test_connect_and_close(self, oracle_connected_db):
        db = oracle_connected_db
        assert db.is_connected is True
        await db.close()
        assert db.is_connected is False

    @pytest.mark.asyncio
    async def test_is_alive(self, oracle_connected_db):
        assert await oracle_connected_db.is_alive() is True

    @pytest.mark.asyncio
    async def test_insert_execute_and_last_id(self, oracle_connected_db):
        db = oracle_connected_db
        await db._execute_raw(
            "BEGIN EXECUTE IMMEDIATE 'DROP TABLE usuarios'; "
            "EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;"
        )
        await db._execute_raw(
            "CREATE TABLE usuarios ("
            "id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY, "
            "nombre VARCHAR2(50))"
        )

        assert await db.execute(db.insert("usuarios", {"nombre": "Héctor"})) == 1
        assert await db.last_id() == 1

        await db.execute(db.insert("usuarios", {"nombre": "Ana"}))
        assert await db.last_id() == 2

        rows = await db.fetch_all(Query("SELECT * FROM usuarios ORDER BY id", []))
        assert [r["nombre"] for r in rows] == ["Héctor", "Ana"]


@pytest.mark.integration
@pytest.mark.optional_engine
class TestOracleParity:
    """DIAL-03/DIAL-09: `count`/`paginate`/`list_tables`/`sync_schema`/`last_id`."""

    @pytest.mark.asyncio
    async def test_count_paginate_and_list_tables(self, oracle_connected_db):
        db = oracle_connected_db
        await _reset_parity(db, _PARITY_DDL)
        await _seed_parity(db)

        assert await _ParityModel(db).count() == 3
        assert await _ParityModel(db).count(Filter.eq("nombre", "Ana")) == 1

        rec = await _ParityModel(db).paginate(limit=2, page=1)
        assert rec.total == 3
        assert len(rec.rows) == 2
        assert rec.limit == 2
        assert rec.page == 1

        tablas = await db.list_tables(limit=1000)
        assert tablas.total >= 1
        assert "test_parity" in {r["name"].lower() for r in tablas.rows}

    @pytest.mark.asyncio
    async def test_query_builder_aggregates(self, oracle_connected_db):
        db = oracle_connected_db
        await _reset_parity(db, _PARITY_DDL)
        await _seed_parity(db)

        qb = _ParityModel(db).query()
        assert await qb.count() == 3
        assert await qb.sum("monto") == 60.0
        assert await qb.avg("monto") == 20.0
        assert await qb.min("monto") == 10.0
        assert await qb.max("monto") == 30.0

    @pytest.mark.asyncio
    async def test_query_builder_limit_first_exists(self, oracle_connected_db):
        # WR-03: `limit().all()`, `first()` y `exists()` deben ser válidos en el
        # motor real (la paginación la aplica el adaptador, sin `LIMIT` en línea).
        db = oracle_connected_db
        await _reset_parity(db, _PARITY_DDL)
        await _seed_parity(db)

        # `order_by` EXPLÍCITO: `fetch_many` de MSSQL inyecta `ORDER BY (SELECT NULL)`
        # cuando falta, y sin orden la paginación no es determinista.
        p1 = await _ParityModel(db).query().order_by("nombre").limit(2).all()
        assert [r["nombre"] for r in p1] == ["Ana", "Eva"]

        p2 = await _ParityModel(db).query().order_by("nombre").limit(2, page=2).all()
        assert [r["nombre"] for r in p2] == ["Luis"]

        first = await _ParityModel(db).query().order_by("nombre").first()
        assert first["nombre"] == "Ana"

        assert (await _ParityModel(db).query().where(Filter.eq("nombre", "Ana")).exists()) is True
        assert (await _ParityModel(db).query().where(Filter.eq("nombre", "Zzz")).exists()) is False

    @pytest.mark.asyncio
    async def test_sync_schema_adds_missing_column(self, oracle_connected_db):
        db = oracle_connected_db
        await _reset_parity(db, _PARITY_DDL_SIN_MONTO)

        result = await _ParityModel(db).sync_schema()
        assert "monto" in result["added"]

        cols = {c.name.lower() for c in await db.columns_of("test_parity")}
        assert "monto" in cols

    @pytest.mark.asyncio
    async def test_last_id_characterization(self, oracle_connected_db):
        db = oracle_connected_db
        await _reset_parity(db, _PARITY_DDL)

        await db.execute(db.insert("test_parity", {"nombre": "Ana"}))
        assert await db.last_id() == 1

        await db.execute(db.insert("test_parity", {"nombre": "Luis"}))
        assert await db.last_id() == 2

    @pytest.mark.asyncio
    async def test_model_insert_replace_no_rompe_el_merge(self, oracle_connected_db):
        # GUARD WR-05 / T-02-45b (CARACTERIZACIÓN, no ejecutabilidad): `Model.insert(
        # replace=True)` deja `conflict=None` en `merge`, así que el MERGE usa el
        # fallback `columns[0]` (`enabled`) y NO referencia `src.id` (columna ausente
        # del `src` derivado) — eso lo prueba el guard DB-free de
        # `test_dialect_builders.py`.
        #
        # A diferencia de MSSQL, la sentencia NO es EJECUTABLE en Oracle por un
        # defecto PREEXISTENTE del render `merge`, ajeno a este plan y NO corregido
        # aquí porque el SQL del adaptador está pinado byte a byte (golden strings y
        # snapshots): el `WHEN MATCHED THEN UPDATE SET` actualiza la MISMA columna que
        # el `ON` (el fallback `columns[0]`), y Oracle lo rechaza con ORA-38104. El
        # `FROM dual` que Oracle exige en el `USING` sí se añade a nivel de driver
        # (`oracle.py`), de modo que el fallo caracterizado es el defecto de fondo.
        # NO se asserta `count()`. Si el builder se corrige, este test avisará.
        db = oracle_connected_db
        await _reset_parity(db, _PARITY_DDL)

        await _MergeModel(db, nombre="Ana", monto=10.0).insert()
        with pytest.raises(Exception) as exc:
            await _MergeModel(db, nombre="Zoe", monto=5.0).insert(replace=True)
        assert "ORA-38104" in str(exc.value)
