from contextlib import asynccontextmanager
from typing import Annotated, ClassVar

import pytest
from pydantic import Field

from encino_orm.model import Column, Model, ddl_type, to_ddl
from encino_orm.query import Query


class Agente(Model):
    _table = "agentes"
    agente: Annotated[str, Column(name="nombre")] = Field(default=None)
    monto: Annotated[float, Column(datatype="numeric")] = Field(default=0.0)
    region_id: int | None = None


class Legacy(Model):
    _table = "legacy"
    _fields_disabled: ClassVar[list] = ["enabled", "created_at", "updated_at"]
    id: Annotated[int, Column(name="legacy_id")] = None
    nota: str | None = None


class Renombrado(Model):
    """PK autoincremental renombrada en la BD (regresión CR-01)."""

    _table = "renombrado"
    id: Annotated[int | None, Column(name="legacy_id")] = None
    nota: str | None = None


class _CapturingDb:
    """`Db` mínimo que captura el `returning` que `Model.insert` pide."""

    def __init__(self):
        self.returning = "unset"

    async def retry(self, coro):
        return await coro()

    @asynccontextmanager
    async def transaction(self):
        yield

    def insert(
        self,
        tabla,
        data,
        ignore_duplicated=False,
        replace=False,
        conflict=None,
        *,
        schema=None,
        returning=None,
    ):
        self.returning = returning
        return Query("INSERT INTO renombrado (nota) VALUES ({0})", [data.get("nota")])

    async def execute_insert(self, qry):
        return 7


async def test_insert_usa_la_columna_fisica_de_la_pk_auto():
    """CR-01: `Model.insert` pide `RETURNING <columna FÍSICA>` de la PK, no el
    nombre del campo `id`; con una PK renombrada el SQL apuntaba a una columna
    inexistente en PostgreSQL/MSSQL/Oracle."""
    db = _CapturingDb()
    obj = Renombrado(db=db, nota="x")
    new_id = await obj.insert()
    assert db.returning == "legacy_id"
    assert new_id == 7


def test_to_ddl_sqlite():
    ddl = to_ddl(Agente, "sqlite")
    assert "CREATE TABLE agentes" in ddl
    assert "id INTEGER PRIMARY KEY AUTOINCREMENT" in ddl
    assert "nombre TEXT" in ddl
    assert "monto REAL" in ddl
    assert "region_id INTEGER" in ddl
    assert "enabled INTEGER" in ddl


def test_to_ddl_mysql():
    ddl = to_ddl(Agente, "mysql")
    assert "id INT AUTO_INCREMENT PRIMARY KEY" in ddl
    assert "nombre VARCHAR(255)" in ddl
    assert "monto DECIMAL(10,2)" in ddl


def test_to_ddl_postgres():
    ddl = to_ddl(Agente, "postgresql")
    assert "id SERIAL PRIMARY KEY" in ddl
    assert "nombre TEXT" in ddl
    assert "monto NUMERIC" in ddl
    assert "enabled BOOLEAN" in ddl


def test_to_ddl_respects_disabled_and_alias():
    ddl = to_ddl(Legacy, "sqlite")
    assert "legacy_id INTEGER PRIMARY KEY AUTOINCREMENT" in ddl
    assert "nota TEXT" in ddl
    assert "enabled" not in ddl
    assert "created_at" not in ddl


def test_ddl_type_unknown_engine():
    with pytest.raises(ValueError):
        to_ddl(Agente, "mongodb")


def test_to_ddl_mariadb():
    ddl = to_ddl(Agente, "mariadb")
    assert "id INT AUTO_INCREMENT PRIMARY KEY" in ddl
    assert "nombre VARCHAR(255)" in ddl
    assert "monto DECIMAL(10,2)" in ddl


def test_to_ddl_mssql():
    ddl = to_ddl(Agente, "mssql")
    assert "id INT IDENTITY(1,1) PRIMARY KEY" in ddl
    assert "nombre NVARCHAR(255)" in ddl
    assert "monto DECIMAL(10,2)" in ddl


def test_to_ddl_oracle():
    ddl = to_ddl(Agente, "oracle")
    assert "id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY" in ddl
    assert "nombre VARCHAR2(255)" in ddl
    assert "monto NUMBER(10,2)" in ddl


def test_ddl_type_postgresql():
    assert ddl_type("str", "postgresql") == "TEXT"
    assert ddl_type("json", "postgresql") == "JSONB"
    assert ddl_type("bool", "postgresql") == "BOOLEAN"
