import os

import pytest

from encino_orm import OracleDb, Query
from encino_orm.introspection.types import _normalize
from encino_orm.model.types import ddl_type
from encino_orm.oracle import _to_oracle

ORACLE_CONFIG = {
    "host": os.getenv("ENCINO_ORM_ORACLE_HOST", "127.0.0.1"),
    "port": int(os.getenv("ENCINO_ORM_ORACLE_PORT", "1521")),
    "service_name": os.getenv("ENCINO_ORM_ORACLE_SERVICE", "XEPDB1"),
    "user": os.getenv("ENCINO_ORM_ORACLE_USER", "system"),
    "password": os.getenv("ENCINO_ORM_ORACLE_PASSWORD", "admin"),
}


class _FakeError:
    def __init__(self, code):
        self.code = code


class _FakeExc(Exception):
    def __init__(self, code):
        self.args = (_FakeError(code),)


class TestOracleInternal:
    def test_to_oracle_named_binds(self):
        q = Query("SELECT * FROM t WHERE a = {0} AND b = {1}", [1, "x"])
        sql, values = _to_oracle(q.query[0], q.query[1])
        assert sql == "SELECT * FROM t WHERE a = :parameter_0000 AND b = :parameter_0001"
        assert values == {"parameter_0000": 1, "parameter_0001": "x"}

    def test_insert_builder_with_returning(self):
        db = OracleDb()
        sql, values = db._prepare(db.insert("t", {"a": 1, "b": "x"}))
        assert sql == (
            "INSERT INTO t (a,b) VALUES (:parameter_0000,:parameter_0001) "
            "RETURNING id INTO :ret_id"
        )
        assert values == {"parameter_0000": 1, "parameter_0001": "x"}

    def test_insert_builder_ignore_duplicated_flag(self):
        db = OracleDb()
        q = db.insert("t", {"a": 1}, ignore_duplicated=True)
        assert q.ignore_duplicated is True
        sql, _ = db._prepare(q)
        assert sql == "INSERT INTO t (a) VALUES (:parameter_0000) RETURNING id INTO :ret_id"

    def test_insert_builder_replace_merge_no_as(self):
        db = OracleDb()
        q = db.insert("t", {"a": 1, "b": "x"}, replace=True)
        sql, values = db._prepare(q)
        assert sql == (
            "MERGE INTO t dst USING (SELECT :parameter_0000 AS a, :parameter_0001 AS b) src "
            "ON (dst.a = src.a) "
            "WHEN MATCHED THEN UPDATE SET dst.a = src.a, dst.b = src.b "
            "WHEN NOT MATCHED THEN INSERT (a,b) VALUES (src.a,src.b)"
        )
        assert values == {"parameter_0000": 1, "parameter_0001": "x"}

    def test_update_builder(self):
        db = OracleDb()
        sql, values = db._prepare(db.update("t", {"id": 1}, {"nombre": "mod"}))
        assert sql == "UPDATE t SET nombre = :parameter_0000 WHERE id = :parameter_0001"
        assert values == {"parameter_0000": "mod", "parameter_0001": 1}

    def test_is_unique_violation(self):
        db = OracleDb()
        assert db.is_unique_violation(_FakeExc(1)) is True       # ORA-00001
        assert db.is_unique_violation(_FakeExc(2291)) is False   # ORA-02291 FK

    def test_is_lock_error(self):
        db = OracleDb()
        assert db.is_lock_error(_FakeExc(60)) is True     # ORA-00060 deadlock
        assert db.is_lock_error(_FakeExc(54)) is True     # ORA-00054 lock timeout
        assert db.is_lock_error(_FakeExc(8177)) is True   # ORA-08177 serialization
        assert db.is_lock_error(_FakeExc(1)) is False

    def test_normalize_new_types(self):
        assert _normalize("varchar2(255)") == ("str", 255, False)
        assert _normalize("nvarchar2(100)") == ("str", 100, False)
        assert _normalize("clob")[0] == "str"
        assert _normalize("blob")[0] == "blob"
        assert _normalize("raw(16)")[0] == "blob"
        assert _normalize("binary_double")[0] == "float"

    def test_ddl_map(self):
        assert ddl_type("pk", "oracle") == "NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY"
        assert ddl_type("str", "oracle") == "VARCHAR2(255)"
        assert ddl_type("bool", "oracle") == "NUMBER(1)"
        assert ddl_type("json", "oracle") == "CLOB"


@pytest.fixture
async def oracle_connected_db():
    db = OracleDb()
    try:
        await db.connect(**ORACLE_CONFIG)
    except Exception as e:
        pytest.skip(f"Oracle no disponible: {e}")
    yield db
    await db.close()


class TestOracleLifecycle:
    @pytest.mark.asyncio
    async def test_connect_and_close(self, oracle_connected_db):
        db = oracle_connected_db
        assert db.is_connected is True
        await db.close()
        assert db.is_connected is False

    @pytest.mark.asyncio
    async def test_is_alive(self, oracle_connected_db):
        assert await oracle_connected_db.is_alive() is True

    @pytest.mark.asyncio
    async def test_insert_execute_and_last_id(self, oracle_connected_db):
        db = oracle_connected_db
        await db._execute_raw(
            "BEGIN EXECUTE IMMEDIATE 'DROP TABLE usuarios'; "
            "EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;"
        )
        await db._execute_raw(
            "CREATE TABLE usuarios ("
            "id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY, "
            "nombre VARCHAR2(50))"
        )

        assert await db.execute(db.insert("usuarios", {"nombre": "Héctor"})) == 1
        assert await db.last_id() == 1

        await db.execute(db.insert("usuarios", {"nombre": "Ana"}))
        assert await db.last_id() == 2

        rows = await db.fetch_all(Query("SELECT * FROM usuarios ORDER BY id", []))
        assert [r["nombre"] for r in rows] == ["Héctor", "Ana"]
